### SIGN-UP
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "chibbycat@mail.com",
  "password": "chibbythecat"
}

### SIGN-IN
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "chibbycat@mail.com",
  "password": "chibbythecat" 
}

# kuchicat@mail.com
# kuchithecat

### Check Current User
GET http://localhost:3000/auth/whoami

### SIGN-OUT
POST http://localhost:3000/auth/signout