### SIGN-UP
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "nalacat@mail.com",
  "password": "nalathecat"
}

### SIGN-IN
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "nalacat@mail.com",
  "password": "nalathecat" 
}

# kuchicat@mail.com
# kuchithecat

### Check Current User
GET http://localhost:3000/auth/whoami

### Check Admin Status
GET http://localhost:3000/auth/checkadmin


### SIGN-OUT
POST http://localhost:3000/auth/signout