### SIGN-UP
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "kuchicat@mail.com",
  "password": "kuchithecat"
}

### SIGN-IN
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "chibbycat@mail.com",
  "password": "chibbythecat" 
}

# kuchicat@mail.com
# kuchithecat

### Check Current User
GET http://localhost:3000/auth/whoami

### Get the currently signed in User via Data Source Manager
GET http://localhost:3000/auth/whoamidatasource

### Check Admin Status
GET http://localhost:3000/auth/checkadmin

### Get a User with provided id
GET http://localhost:3000/auth/2

### SIGN-OUT
POST http://localhost:3000/auth/signout